---
- hosts: masters{% if (master_node_vms|int > 1) %},lb{% endif %}{% if infra_node_vms is defined and infra_node_vms > 0%},infra_nodes{% endif %}
  gather_facts: false
  roles:
    - role: subscription_attach
      pool_name: "{{subs.broker_sub_pool}}"
      pool_id: "{{subs.broker_sub_pool_id|default(false)}}"
      when: deploy_type == 'ocp' and operate == 'deploy'

- hosts: app_nodes
  gather_facts: false
  roles:
    - role: subscription_attach
      pool_name: "{{subs.node_sub_pool}}"
      pool_id: "{{subs.node_sub_pool_id|default(false)}}"
      when: deploy_type == 'ocp' and operate == 'deploy'


- hosts: localhost {% if (deploy_type == 'scale' and operte == 'up') or (deploy_type == 'bg_upgrade' and operate == 'upgrade')  %}, new_nodes {% endif %}
  roles:
    - role: subscription_attach
      pool_name: "{{subs.broker_sub_pool}}"
      pool_id: "{{subs.broker_sub_pool_id|default(false)}}"
      when: inventory_hostname in broker_sub_nodes

    - role: subscription_attach
      pool_name: "{{subs.node_sub_pool}}"
      pool_id: "{{subs.node_sub_pool_id|default(false)}}"
      when: inventory_hostname in node_sub_nodes

