#Copy Public Key

# Cluster Installation
- hosts: localhost
  gather_facts: false
  tasks:
   - debug: var=deploy_type
   - name: Set up SSH public 
     block:
      - name: Delete hosts from known_hosts
        lineinfile:
          path: ~/.ssh/known_hosts
          state: absent
          regexp: "{{item}}"
        with_items:
          - "{{groups['all_nodes']}}"
  
      - name: For each host, ssh-copy-id my ssh public keys to the host
        shell: "sshpass -p {{base_image.pw}} ssh-copy-id -o StrictHostKeyChecking=no -i {{ssh_public_key}} {{base_image.id}}@{{item}}; sleep 3"
        with_items:
          - "{{groups['all_nodes']}}"
     when: deploy_type == 'ocp_cluster'


# Scaling - For New Nodes
- hosts: localhost
  gather_facts: false
  tasks:
   - name: Set up SSH public 
     block:
      - name: Delete hosts from known_hosts
        lineinfile:
          path: ~/.ssh/known_hosts
          state: absent
          regexp: "{{item}}"
        with_items:
          - "{{groups['new_nodes']}}"
  
      - name: For each host, ssh-copy-id my ssh public keys to the host
        shell: "sshpass -p {{base_image.pw}} ssh-copy-id -o StrictHostKeyChecking=no -i {{ssh_public_key}} {{base_image.id}}@{{item}}; sleep 3"
        with_items:
          - "{{groups['new_nodes']}}"
     when: deploy_type == 'infra' or deploy_type == 'app'
