# Distinguish Each Cluster
# tag: 3.6
prefix_vm: jlee

# Ansible
# ansible_controller_hostname: ansible.example.com
# if ansible_controller_hostname is set, it will check localhost hostname is the same. If not, it fails.
# if ansible_controller_hsotanme is unset, one of master will be used as ansible controller.

ssh_public_key: '/home/jooho/.ssh/id_rsa.pub'
ansible_controller_hostname: ansible.example.com

# Base Image Info
base_image:
  os: rhel
  version: 7u3
  rhev_os_type: 7x64
  id: "{{lookup('env', 'BASE_IMAGE_ID')}}"
  pw: "{{lookup('env', 'BASE_IMAGE_PW')}}"

# RHEV Info
rhev:
  template: RHEL_7U3_for_OCP
  cluster: Test
  id: "{{lookup('env', 'RHEV_ID')}}"
  pw: "{{lookup('env', 'RHEV_PW')}}"
  ca_file: "{{lookup('env', 'RHEV_CA_PATH')}}"
  api_url: "{{lookup('env', 'RHEV_API_URL')}}"
 
# Subscription Info
subs:
  id: "{{lookup('env', 'RHSM_ID')}}"
  pw: "{{lookup('env', 'RHSM_PW')}}"
  broker_sub_pool: "Red Hat OpenShift Container Platform Broker/Master Infrastructure"
  node_sub_pool: "Red Hat OpenShift Container Platform, Standard, 2-Core"

# OpenShift Info
# package_version: 3.3.19

ocp:
  version: 3.3

# Openshift Cluster VMs
# if infra_node_vms is not specified, it assumes app node have "region=infra" labels  
# infra_node_vms
# if etcd_node_vms is not specified, etcd will be deploying on masters
# etcd_node_vms
master_node_vms: 2
app_node_vms: 2
etcd_node_vms: 1


# If etcd_vms is specified, etcd will be installed separately.
# etcd_vms:3

# OpenShift parameters
metrics: 
  enable: true
  hawkular_hostname: hawkular."{{subdomain}}"

logging:
  enable: true
  kibana_hostname: kibana."{{subdomain}}"

# Extra VMs
# ldap: 
#   install: true
#   target_vm: infra_node
# nfs:
#   install: true
#   target_vm: infra_node
#   


# ETC
loglevel: debug







# OSE Cluster
