---
- name: Add masters to host groups
  add_host:
    name: "{{ hostvars[item].fqdn}}"
    groups: all_nodes, masters {% if etcd_node_vms is not defined %}, etcd {% endif %}, nodes, broker_sub_nodes
    openshift_node_labels:
      'role': 'master'
      'region': 'mgmt'
  with_items: "{{groups['tag_Name_' + cluster_tag +'_master_node_vms']}}"


- name: Add infra instances to host group
  add_host:
    name: "{{ hostvars[item].fqdn}}"
    groups: all_nodes, nodes, infra_nodes, broker_sub_nodes 
    openshift_node_labels:
      role: infra
      region: infra
      zone: default
  with_items: "{{groups['tag_Name_' + cluster_tag +'_infra_node_vms']}}"
  when: infra_node_vms is defined and infra_node_vms > 0


- name: Add App instances to host group
  add_host:
    name: "{{ hostvars[item].fqdn}}"
    groups: all_nodes, nodes, app_nodes, node_sub_nodes 
    openshift_node_labels:
      role: app
      region: "{% if infra_node_vms is not defined %}infra  {% else %}app {% endif %}"
      zone: default
  with_items: "{{groups['tag_Name_' + cluster_tag +'_app_node_vms']}}"
  when: app_node_vms is defined and app_node_vms > 0


- name: Add ETCD instances to host group
  add_host:
    name: "{{ hostvars[item].fqdn}}"
    groups: all_nodes, etcd, broker_sub_nodes
  with_items: "{{groups['tag_Name_' + cluster_tag +'_etcd_node_vms']}}"
  when: etcd_node_vms is defined and etcd_node_vms > 0

- name: Add Master instances to ETCD host group
  add_host:
    name: "{{ hostvars[item].fqdn}}"
    groups: all_nodes, etcd, broker_sub_nodes
  with_items: "{{groups['tag_Name_' + cluster_tag +'_master_node_vms']}}"
  when: etcd_node_vms is not defined

- name: Print ETCD List 
  debug: var={{item}}
  with_items: groups['etcd']
  when: loglevel is defined and loglevel == "debug"

- name: Add LB instances to host group
  add_host:
    name: "{{ hostvars[item].fqdn }}"
    groups: all_nodes, lb, broker_sub_nodes
    openshift_node_labels:
      role: lb
  with_items: "{{groups['tag_Name_' + cluster_tag +'_lb_node_vms']}}"
  when: master_node_vms|int > 1 

# Scaling (all_nodes -> ssh-id-copy, new_nodes -> scaleup, broker/node_sub_nodes -> scale/bg_upgrade)
- name: Add New Infra instances to host group
  add_host:
    name: "{{ hostvars[item].fqdn}}"
    groups: all_nodes, broker_sub_nodes, new_nodes
    openshift_node_labels:
      role: infra
      region: infra
      zone: default
  with_items: "{{groups['tag_Name_new_' + cluster_tag +'_infra_node_vms']}}"
  when: deploy_type == "scale" and operate == 'up' and scale_target == 'infra'


- name: Add New App instances to host group
  add_host:
    name: "{{ hostvars[item].fqdn}}"
    groups: all_nodes, node_sub_nodes, new_nodes 
    openshift_node_labels:
      role: app
      region: app
      zone: default
  with_items: "{{groups['tag_Name_new_' + cluster_tag +'_app_node_vms']}}"
  when: deploy_type == "scale" and operate == 'up' and scale_target == 'app'

# GB (all_nodes -> ssh-id-copy, new_nodes -> scaleup, infra/app_nodes_{{new_cluster_tag}} -> start/stop/teardown)
- name: Add New Infra instances for GB to host group 
  add_host:
    name: "{{ hostvars[item].fqdn}}"
    groups: all_nodes{% if operate == 'deploy' %},new_nodes,infra_nodes_{{new_cluster_tag}}{% else %},infra_nodes_{{new_cluster_tag}}{% endif %}
    openshift_node_labels:
      role: infra
      region: infra
      zone: default
      color: "{{ new_cluster_tag }}"
    openshift_schedulable: false
  with_items: "{{groups['tag_Name_' + cluster_tag +'_infra_node_vms_' + new_cluster_tag]}}"
  when: deploy_type == 'bg_upgrade' and target == 'node'


- name: Add New App instances for GB to host group
  add_host:
    name: "{{ hostvars[item].fqdn}}"
    groups: all_nodes{% if operate == 'deploy' %},new_nodes,app_nodes_{{new_cluster_tag}}{% else %},app_nodes_{{new_cluster_tag}}{% endif %}
    openshift_node_labels:
      role: app
      region: app
      zone: default
      color: "{{ new_cluster_tag }}"
    openshift_schedulable: false
  with_items: "{{groups['tag_Name_' + cluster_tag +'_app_node_vms_' + new_cluster_tag]}}"
  when: deploy_type == 'bg_upgrade' and target == 'node'



#- name: Print Node label List 
#  debug: msg={{hostvars['dhcp182-109.gsslab.rdu2.redhat.com'].openshift_node_labels}}
#  when: loglevel is defined and loglevel == "debug"


#- name: Print Node label List 
#  debug: msg={{hostvars[groups.infra_nodes.0].openshift_node_labels}}
#  when: loglevel is defined and loglevel == "debug"
#
#- name: Print Node List 
#  debug: msg={{hostvars[item].openshift_node_labels}}
#  with_items: "{{groups.masters}}"
#  when: loglevel is defined and loglevel == "debug"

#- name: Print Node label List 
#  debug: msg="{{hostvars[item].openshift_node_labels}}"
#  with_items: "{{groups['nodes']}}"
#  when: loglevel is defined and loglevel == "debug"

#- name: Print ETCD label List 
#  debug: msg="{{item}}]"
#  with_items: "{{groups['etcd']}}"
#  when: loglevel is defined and loglevel == "debug"

#- name: Print LB label List 
#  debug: msg="{{item}}"
#  with_items: "{{groups['lb']}}"
#  when: loglevel is defined and loglevel == "debug"
