---
- hosts: localhost
  tasks: 
    - name: Update groups
      include: "../{{provider}}/tasks/generate-host-groups.yaml"

- name: Deploy metrics
  include: /usr/share/ansible/openshift-ansible/playbooks/byo/openshift-cluster/openshift-metrics.yml
  vars:
     openshift_metrics_install_metrics: True
     openshift_metrics_hawkular_hostname: "hawkular-metrics.{{ocp_cluster_subdomain}}"
  when: operate == 'deploy' and target is not defined

- name: Upgrade metrics
  include: /usr/share/ansible/openshift-ansible/playbooks/byo/openshift-cluster/openshift-metrics.yml
  vars:
     openshift_hosted_metrics_deploy: true 
     openshift_hosted_metrics_deployer_version: "v{{ocp_version}}"
     openshift_metrics_hawkular_hostname: "hawkular-metrics.{{ocp_cluster_subdomain}}"
  when: operate == 'upgrade' and target is not defined

- name: Delete metrics
  include: /usr/share/ansible/openshift-ansible/playbooks/byo/openshift-cluster/openshift-metrics.yml
  vars:
    openshift_metrics_install_metrics: False
  when: operate == 'undeploy' and target is not defined

- hosts: masters[0]
  tasks: 
    - name: Deploy metrics agent
      block: 
        - name: Download hawkular-openshift-agent-configmap & hawkular-openshift-agent
          get_url:
             url: "{{item}}"
             dest: /tmp/{{item|baseurl}}"  
             mode: 777
          with_items:
             - "https://github.com/openshift/origin-metrics/blob/enterprise/hawkular-openshift-agent/hawkular-openshift-agent-configmap.yaml"
             - "https://github.com/openshift/origin-metrics/blob/enterprise/hawkular-openshift-agent/hawkular-openshift-agent.yaml"
    
        - name: Create configmap & pod for hawkular agent
          command: "{{item}}"
          with_items:
            - "oc create -f /tmp/hawkular-openshift-agent-configmap.yaml -n default"
            - "oc process -f /tmp/hawkular-openshift-agent.yaml | oc create -n default -f -"
            - "oc adm policy add-cluster-role-to-user hawkular-openshift-agent system:serviceaccount:default:hawkular-openshift-agent"
      when: operate == 'deploy' and target is defined and target == 'agent'
    
    - name: Undeploy metrics agent
      command: "oc delete all,secrets,sa,templates,configmaps,daemonsets,clusterroles --selector=metrics-infra=agent -n default"
      when: operate == 'undeploy' and target is defined and target == 'agent' 

   
     
