---
- hosts: localhost
  pre_tasks:
    - include: ./validate.yaml
    - set_fact:
        ansible_controller_ip: "{{hostvars[inventory_hostname]['ansible_default_ipv4']['address']}}"
    - debug: var=ansible_controller_ip
  roles:
    - { role: create_vms }
  post_tasks:
    - name: Update groups
      include: ./generate-host-groups.yaml
    - name: Install interim dns 
      include_role:
        name: interim_dns


# Copy Public Key 
- hosts: localhost
  gather_facts: false
  tasks:
   - name: For each host, ssh-copy-id my ssh public keys to the host
     shell: "sshpass -p {{base_image.pw}} ssh-copy-id -o StrictHostKeyChecking=no -i {{ssh_public_key}} {{base_image.id}}@{{item}}; sleep 3"
     with_items:
       - "{{groups['all_nodes']}}"
     tags:
      - sshcopy

# RHSM
- hosts: masters {% if infra_node_vms is defined %}, infra {% endif %} 
  gather_facts: false
  roles: 
    - role: subscription_attach
      pool_name: "{{subs.broker_sub_pool}}"
      pool_id: "{{subs.broker_sub_pool_id|default(false)}}"
  tags: rhsm 


- hosts: app_nodes
  gather_facts: false
  roles: 
    - role: subscription_attach
      pool_name: "{{subs.node_sub_pool}}"
      pool_id: "{{subs.node_sub_pool_id|default(false)}}"
  tags: rhsm 


# host_prerequisite
- hosts: masters, infra_nodes, app_nodes
  tasks:
    - name: Install Host Requisites
      include: ./host_prerequisite.yaml

    - name: Inall Ansible Controller Requisites
      include: ./ansible-controller-prerequisite.yaml
      delegate_to: localhost

    - name: Check if iterim dns ip exist in /etc/resolv.conf
      command: "grep {{hostvars['localhost']['ansible_controller_ip']}} /etc/resolv.conf"
      register: interim_dns_ip_exist
      ignore_errors: yes

    - name: Add interim dns ip to all nodes
      lineinfile:
        path: /etc/resolv.conf
        line: "{{item}} {{interim_dns.master_internal_api_hostname}}"
      with_items:
        - "{{ interim_dns_ip_exist }}"
      when: item.rc == 1
 
  
# Run cluster installation playbook
- include: /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml
