---
- hosts: localhost
  pre_tasks:
    - debug: var=ocp_version
    - name: Validate Subscription Pool is specified
      fail: msg="Validate Subscription Pool is specified"
      when: not lookup('env', 'BROKER_SUB_POOL_ID') or not lookup('env', 'BROKER_SUB_POOL')

    - name: Create Ansible Controller VM from template
      ovirt_vms:
         name: "{{prefix_vm}}_ansible_controller_1"
         template: "{{rhev.template}}"
         cluster: "{{rhev.cluster}}"
         auth:
           username: "{{rhev.id}}"
           password: "{{rhev.pw}}"
           url: "{{rhev.api_url}}"
           ca_file: "{{rhev.ca_file}}"
         operating_system: "{{base_image.os}}_{{base_image.rhev_os_type}}"
         state: running
         wait: True
      register: created_ansible_controller_vm_info

    - name: Watiting until fqdn is set
      block:
        - name: Gather Ansible Controller VM info
          ovirt_vms_facts:
            pattern: "name={{created_ansible_controller_vm_info.vm.name}}"
            auth:
              username: "{{rhev.id}}"
              password: "{{rhev.pw}}"
              url: "{{rhev.api_url}}"
              ca_file: "{{rhev.ca_file}}"
          register: vms_info
          until: vms_info.ansible_facts.ovirt_vms[0].fqdn is defined
          ignore_errors: yes
          retries: 60
          delay: 10

    - name: Refresh inventory to ensure new instaces exist in inventory
      meta: refresh_inventory

    - name: Add ansible controller to memory
      add_host:
        name: "{{vms_info.ansible_facts.ovirt_vms[0].fqdn}}"
        groups: ansible-controller

  roles:
    - role: ssh-id-copy
      ssh_id_copy_target: "{{vms_info.ansible_facts.ovirt_vms[0].fqdn}}"


- hosts: ansible-controller
  tasks:
    - name: Register RHSM for Ansible Controller
      include_role:
         name: subscription_attach
      vars:
         pool_name: "{{subs.broker_sub_pool  | default(false)}}"
         pool_id: "{{subs.broker_sub_pool_id  | default(false)}}"

    - name: Prerequisite for ansible controller
      include_role:
        name: openshift-prerequisites
      vars:
        node_type: ansible-controller 

    
    - name: Install essential packages
      yum: 
        name: "{{ item }}"
        state: present
      with_items:
        - wget 
        - git 
        - net-tools
        - bind-utils 
        - iptables-services 
        - bridge-utils 
        - bash-completion 
        - kexec-tools 
        - sos
        - psacct 
        - python 
        - gcc 
        - libxml2-devel
        - python-devel
        - sshpass 
        - atomic-openshift-utils
 
    - name: Download get-pip.py for pip packaging util
      get_url:
         url: https://bootstrap.pypa.io/get-pip.py
         dest: /tmp/get-pip.py
         mode: 777
    
    - name: Install pip
      command: "python /tmp/get-pip.py"
  
    - name: Install ovirt-engine-sdk-python
      command: "{{ item }}"
      with_items:
        -  "pip install ovirt-engine-sdk-python "
        -  "pip install ansible==2.3.1.0"
  
    - name: Check out official ansible github repository
      git: 
        repo: "{{ item.url }}"
        dest: "/root/git/{{ item.folder_name }}"   
      with_items:
        - { url: 'https://github.com/ansible/ansible.git', folder_name: 'ansible' }
        - { url: 'https://github.com/Jooho/ansible-cheat-sheet.git', folder_name: 'ansible-cheat-sheet' }

## 2.4 is releasd so it does not need anymore
#    - name: Gather file info for modules
#      command: "ls -al /root/git/ansible/lib/ansible/modules/cloud/ovirt/ovirt*"
#      register: ovirt_module_files
#
#   - name: Copy some latest modules to ansible-cheat-sheet repo
#     command: "cp {{ item }} /root/git/ansible-cheat-sheet/ansible-playbooks/ansible-playbook-deploy-ocp-on-rhev/modules"
#     with_items:
#        - "{{ovirt_module_files.stdout_lines}}"
#        - "/root/git/ansible/lib/ansible/modules/packaging/os/redhat_subscription.py"
  
