---
- hosts: localhost
  pre_tasks:
    - set_fact:
        ansible_controller_ip: "{{hostvars[inventory_hostname]['ansible_default_ipv4']['address']}}"
  tasks:
    - include: ./validate.yaml
    - debug: var=ansible_controller_ip

    - name: Create RHEV VM 
      include: ./tasks/create-bg-vms.yaml

    - name: Refresh inventory to ensure new instaces exist in inventory
      meta: refresh_inventory

    - name: Update groups
      include: ./tasks/generate-host-groups.yaml

    - name: generate host file
      include_role:
        name: generate_hosts_file

    - name: Install interim dns 
      include_role:
        name: interim_dns
      when: interim_dns.install

- name: Copy public key to all nodes
  include: ../common/openshift-cluster/ssh-copy-id.yaml

- name: RHSM register subscription
  include: ../common/openshift-cluster/rhsm-register.yaml

# ansible_controller_prerequisite
- name: Inall Ansible Controller Pre-Requisites
  hosts: localhost
  roles:
     - { role: openshift-prerequisites, node_type: ansible-controller }


- name: Install OCP Host Pre-Requisites
  hosts: new_nodes
  roles: 
    - { role: openshift-prerequisites, node_type: ocp-host }


# Deploy Blue Green VMs 
- include: /usr/share/ansible/openshift-ansible/playbooks/byo/openshift-node/scaleup.yml

