---
- hosts: localhost
  pre_tasks:
    - set_fact:
        ansible_controller_ip: "{{hostvars[inventory_hostname]['ansible_default_ipv4']['address']}}"
  tasks:
    - include: ./validate.yaml
    - debug: var=ansible_controller_ip

    - name: Create RHEV VM 
      include: ./tasks/create-ocp-cluster-vms.yaml

    - name: Update groups
      include: ./tasks/generate-host-groups.yaml

    - name: generate host file
      include_role:
        name: generate_hosts_file

    - name: Install interim dns 
      include_role:
        name: interim_dns
      when: interim_dns.install

- name: Copy public key to all nodes
  include: ../common/openshift-cluster/ssh-copy-id.yaml

- name: RHSM register subscription
  include: ../common/openshift-cluster/rhsm-register.yaml

# ansible_controller_prerequisite
- name: Inall Ansible Controller Pre-Requisites
  hosts: localhost
  roles:
     - { role: openshift-prerequisites, node_type: ansible-controller }

- name: Install OCP Host Pre-Requisites
  hosts: masters{% if (master_node_vms|int > 1) %},lb{% endif %}{% if infra_node_vms is defined and infra_node_vms > 0%},infra_nodes{% endif %},{% if app_node_vms is defined and app_node_vms > 0%},app_nodes{% endif %}
  roles: 
    - { role: openshift-prerequisites, node_type: ocp-host, when: groups.lb is defined and inventory_hostname != groups.lb.0 }
    - { role: openshift-prerequisites, node_type: ocp-lb, when: groups.lb is defined and inventory_hostname == groups.lb.0 }


#    - name: Check if iterim dns ip exist in /etc/resolv.conf
#      command: "grep {{hostvars['localhost']['ansible_controller_ip']}} /etc/resolv.conf"
#      register: interim_dns_ip_exist
#      ignore_errors: yes
#
#    - name: Add interim dns ip to all nodes
#      lineinfile:
#        path: /etc/resolv.conf
#        line: "nameserver {{hostvars['localhost']['ansible_controller_ip']}}"
#        insertafter: "search"
#      with_items:
#        - "{{ interim_dns_ip_exist }}"
#      when: item.rc == 1
 
#- hosts: localhost  
#  tasks: 
#    - name: Refresh inventory to ensure new instaces exist in inventory
#      meta: refresh_inventory

# Run cluster installation playbook
- include: /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml
