---
- set_fact:
    need_repo_list:
       - rhel-7-server-rpms
       - rhel-7-server-ose-{{ocp_version}}-rpms
- shell: subscription-manager repos --list-enabled  |grep 'Repo ID'|awk  '{print $3}'
  register: enabled_repo_list

- name: Disable unneeded repositories
  command: subscription-manager repos --disable='*'
  when: need_repo_list|difference(enabled_repo_list.stdout_lines)|length != 0

- name: Enable OpenShift repositories
  command: subscription-manager repos --enable="{{item}}" 
  with_items:
    - "{{ need_repo_list }}"
  when: need_repo_list|difference(enabled_repo_list.stdout_lines)|length != 0


