---

- name: Watiting until fqdn is set
  block:
    - name: Scaling - Gather New Infra VMs info
      ovirt_vms_facts:
        pattern: "name={{item.vm.name}}"
        auth:
          username: "{{rhev.id}}"
          password: "{{rhev.pw}}"
          url: "{{rhev.api_url}}"
          ca_file: "{{rhev.ca_file}}"
      with_items:
        - "{{created_new_node_vms_info.results}}"
      when: (infra_node_vms is defined and infra_node_vms > 0) and (j_deploy_type=='infra')
      register: vms_info
      until: vms_info.ansible_facts.ovirt_vms[0].fqdn is defined
      ignore_errors: yes
      retries: 60
      delay: 10
    
    - name: Scaling - Gather new App VMs info
      ovirt_vms_facts:
        pattern: "name={{item.vm.name}}"
        auth:
          username: "{{rhev.id}}"
          password: "{{rhev.pw}}"
          url: "{{rhev.api_url}}"
          ca_file: "{{rhev.ca_file}}"
      with_items:
        - "{{created_new_node_vms_info.results}}"
      register: vms_info
      until: vms_info.ansible_facts.ovirt_vms[0].fqdn is defined
      ignore_errors: yes
      retries: 60
      delay: 10
      when: app_node_vms is defined and app_node_vms > 0 and j_deploy_type=='app'
    
    
# Scaling (all_nodes -> ssh-id-copy, new_nodes -> scaleup, broker/node_sub_nodes -> scale/bg_upgrade)
- name: Add New Infra instances to host group
  add_host:
    name: "{{ hostvars[item].fqdn}}"
    groups: all_nodes, broker_sub_nodes, new_nodes, new_infra_nodes
    openshift_node_labels:
      role: infra
      region: infra
      zone: default
      logging-infra-fluentd: "true"
  with_items: "{{groups['tag_Name_new_' + cluster_tag +'_infra_'+ target_vm_tag_postfix]}}"
  when: j_deploy_type == "scale" and operate == 'up' and target == 'infra'


- name: Add New App instances to host group
  add_host:
    name: "{{ hostvars[item].fqdn}}"
    groups: all_nodes, node_sub_nodes, new_nodes 
    openshift_node_labels:
      role: app
      region: app
      zone: default
      logging-infra-fluentd: "true"
  with_items: "{{groups['tag_Name_new_' + cluster_tag +'_app_' + target_vm_tag_postfix]}}"
  when: j_deploy_type == "scale" and operate == 'up' and target == 'app'



#- name: Print Node label List 
#  debug: msg={{hostvars['dhcp182-109.gsslab.rdu2.redhat.com'].openshift_node_labels}}
#  when: loglevel is defined and loglevel == "debug"


#- name: Print Node label List 
#  debug: msg={{hostvars[groups.infra_nodes.0].openshift_node_labels}}
#  when: loglevel is defined and loglevel == "debug"
#
#- name: Print Node List 
#  debug: msg={{hostvars[item].openshift_node_labels}}
#  with_items: "{{groups.masters}}"
#  when: loglevel is defined and loglevel == "debug"

#- name: Print Node label List 
#  debug: msg="{{hostvars[item].openshift_node_labels}}"
#  with_items: "{{groups['nodes']}}"
#  when: loglevel is defined and loglevel == "debug"

#- name: Print ETCD label List 
#  debug: msg="{{item}}]"
#  with_items: "{{groups['etcd']}}"
#  when: loglevel is defined and loglevel == "debug"

#- name: Print LB label List 
#  debug: msg="{{item}}"
#  with_items: "{{groups['lb']}}"
#  when: loglevel is defined and loglevel == "debug"
